@startuml 

entity Category

Category : uuid id 
Category : string name 
Category : string description 
Category : date create_at 

Category : create()
Category : update()
Category : activate()
Category : deactivate()
Category : delete()


@enduml